// ============================================
// A CSV must carry every link the record has
// ============================================
// THE BUG. An export that leaves out a link column turns
// export → delete → re-import into silent data loss, and nothing on screen
// says so: where a denormalised name sits beside the id (ship_name next to
// property_id, supplier_name next to supplier_id) the TEXT survives and only
// the LINK breaks. It stays invisible until somebody actually round-trips
// their data.
//
// Found here on 2026-09-14, three ways at once:
//   * accommodation_rates, airport_staff_rates and hotel_staff_rates have a
//     supplier_id their forms fill in, and their CSV had no such column — so
//     every hotel and every airport/hotel service rate came back unlinked from
//     its supplier.
//   * accommodation_rates, nile_cruises, train_rates and sleeping_train_rates
//     have a property_id (the hotel, the ship, the train), and NO rate CSV had
//     a property column at all.
//   * the suppliers page wrote its own file with nine display headers the
//     importer does not recognise, losing supplier_code, every contact field,
//     the website, the address and the notes — the supplier_code loss being
//     the worst, because the DB trigger then mints a NEW SUP-#### and breaks
//     the supplier_code link in every rate CSV exported beside it.
//
// WHY THE TESTS DID NOT CATCH IT. The column set was written down in several
// places — export, sample CSV, importer, tests — with nothing forcing them to
// agree, and the tests asserted against their own fourth copy of the wrong
// list. So this file states the invariant against SOURCES OF TRUTH the CSV
// code does not own:
//
//   * the real schema, built from nothing by replaying migrations/ into a
//     PGlite Postgres (the same replay `npm run replay:schema` gates CI with)
//     and then asked, via information_schema, what columns each table has;
//   * the supplier form's own field list (lib/suppliers/fields.ts) — what a
//     person can actually type in.
//
// NOT types/database.types.ts, though write-contract.test.ts reads it for a
// different invariant: that file is generated by hand from LIVE PRODUCTION
// (`npm run types:generate`, which needs prod credentials) and had drifted —
// it does not contain `supplier_code` at all, months after the column shipped.
// A guard against a stale copy of the schema is the same disease one level up.
// migrations/ is committed, is replayed on every CI run, and IS the schema a
// self-hosted install gets — which is the case cross-install CSV portability
// exists to serve.
//
// A new link column in a migration, or a new field on the supplier form, fails
// this file until the CSV learns about it. There is no copy of the answer kept
// here to fall out of step.
import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest'
import { RATE_TABLE_CONFIGS } from '@/lib/bulk-rate-service'
import { SUPPLIER_FORM_FIELDS } from '@/lib/suppliers/fields'
import { SUPPLIER_CSV_COLUMNS, supplierCsvHeaders } from '@/lib/suppliers/import-csv'
import { replayMigrations, publicTableColumns } from '@/scripts/replay-core.mjs'

// Replaying 46 migrations into a fresh Postgres takes a few seconds, and more
// when vitest is running other PGlite-backed suites alongside. The default 5s
// is a timing assumption, not a correctness one.
vi.setConfig({ testTimeout: 120_000, hookTimeout: 120_000 })

let schema: Map<string, Set<string>>
let db: { close(): Promise<void> }

beforeAll(async () => {
  const replay = await replayMigrations()
  db = replay.db
  // If the replay itself is broken, every assertion below would pass
  // vacuously against an empty schema. `npm run replay:schema` is the gate
  // that reports this properly; here it just must not be silent.
  expect(replay.failed, 'migrations/ did not replay cleanly — run `npm run replay:schema`').toEqual([])
  schema = await publicTableColumns(db)
  expect(schema.size, 'the replayed schema is empty').toBeGreaterThan(100)
})

afterAll(async () => {
  await db?.close()
})

/** Each rate config paired with the columns its real table has. */
function rateConfigsWithSchema() {
  return Object.entries(RATE_TABLE_CONFIGS).map(([key, cfg]) => ({
    key,
    cfg,
    columns: schema.get(cfg.tableName) ?? null,
  }))
}

describe('the rate CSVs, against the database schema', () => {
  it('names a table a fresh install actually builds', () => {
    // fixed_costs is the registry key; fixed_daily_costs is the table. Pointing
    // a config at a table that does not exist made its export and import fail
    // outright once already.
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      expect(columns, `${key} → ${cfg.tableName} does not exist in the replayed schema`).not.toBeNull()
    }
  })

  it('carries supplier_id wherever the table has one', () => {
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      if (!columns?.has('supplier_id')) continue
      expect(
        cfg.columns.map(c => c.name),
        `${key} drops supplier_id: a round-trip unlinks every row from its supplier`,
      ).toContain('supplier_id')
    }
  })

  it('never invents a supplier_id the table does not have', () => {
    // The opposite failure: a column the upsert would send and PostgREST would
    // reject, sinking the whole import.
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      if (!columns || columns.has('supplier_id')) continue
      expect(cfg.columns.map(c => c.name), `${cfg.tableName} has no supplier_id`).not.toContain('supplier_id')
    }
  })

  it('declares a property link wherever the table has a property_id', () => {
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      if (!columns?.has('property_id')) continue
      expect(
        cfg.propertyLink,
        `${key} has a property_id but no propertyLink: a round-trip unlinks every row from the hotel/ship/train it prices`,
      ).toBeDefined()
    }
  })

  it('declares no property link where the table has no property_id', () => {
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      if (!columns || columns.has('property_id')) continue
      expect(cfg.propertyLink, `${cfg.tableName} has no property_id`).toBeUndefined()
    }
  })

  it('carries each property link as a NAME column, never as the UUID', () => {
    // A foreign install's UUID is meaningless; the name under the supplier is
    // the property's unique key (supplier_properties_unique_name) and the one
    // a person reading the sheet recognises.
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      const link = cfg.propertyLink
      if (!link) continue
      const names = cfg.columns.map(c => c.name)
      expect(names, `${key} must carry ${link.nameColumn}`).toContain(link.nameColumn)
      expect(names, `${key} must not export property_id — a UUID does not travel`).not.toContain('property_id')

      // `virtual` says whether the name is a real column on the rate table.
      // Getting it backwards sends an unknown column to the upsert, or drops a
      // stored one, so it is checked against the schema too.
      const stored = columns?.has(link.nameColumn) ?? false
      expect(
        Boolean(link.virtual),
        `${key}: ${link.nameColumn} is ${stored ? '' : 'not '}a column of ${cfg.tableName}`,
      ).toBe(!stored)
    }
  })

  it('never offers a column the table does not have', () => {
    // Every column must be either a real one, or one of the declared virtual
    // keys the import route resolves and strips.
    for (const { key, cfg, columns } of rateConfigsWithSchema()) {
      if (!columns) continue
      const virtual = new Set(['supplier_code'])
      if (cfg.propertyLink?.virtual) virtual.add(cfg.propertyLink.nameColumn)
      for (const c of cfg.columns) {
        if (virtual.has(c.name)) continue
        // Per-vehicle cells fold into the `vehicles` list before the upsert.
        if (/_(rate_eur|rate_non_eur|capacity_min|capacity_max)$/.test(c.name)) continue
        expect(columns.has(c.name), `${key}: ${cfg.tableName} has no column ${c.name}`).toBe(true)
      }
    }
  })
})

describe('the suppliers CSV, against the form and the schema', () => {
  const headers = supplierCsvHeaders()
  const csvColumn = new Map(SUPPLIER_CSV_COLUMNS.map(c => [c.column ?? c.name, c]))

  it('has a column for every field the supplier form collects', () => {
    // The invariant that makes this permanent: a new field on the form fails
    // here until the sheet learns it. The form is the source of truth, not a
    // column count copied into this file.
    for (const field of SUPPLIER_FORM_FIELDS) {
      expect(
        csvColumn.get(field.key),
        `the supplier form collects ${field.key}, and the CSV has no column for it`,
      ).toBeDefined()
    }
  })

  it('writes only columns the suppliers table actually has', () => {
    const columns = schema.get('suppliers')
    expect(columns).toBeDefined()
    for (const c of SUPPLIER_CSV_COLUMNS) {
      expect(columns!.has(c.column ?? c.name), `suppliers has no column ${c.column ?? c.name}`).toBe(true)
    }
  })

  it('carries the portable key, because losing it re-mints every supplier', () => {
    // supplier_code is what a rate CSV resolves a rate back to its supplier
    // with. Dropping it from the roster export means a re-imported supplier
    // gets a brand-new SUP-#### from the DB trigger, and every rate file
    // exported beside it points at a code that no longer exists.
    expect(headers).toContain('supplier_code')
  })

  it('uses importer keys as headers, not display labels', () => {
    // The original defect: the export wrote "Code", "Contact", "Email" — the
    // importer lowercases and underscores each header, so those became `code`,
    // `contact`, `email` and matched nothing.
    const importerKeys = new Set(SUPPLIER_CSV_COLUMNS.map(c => c.name))
    for (const h of headers) {
      expect(h, `${h} is not a key the importer reads`).toBe(h.trim().toLowerCase().replace(/\s+/g, '_'))
      expect(importerKeys.has(h)).toBe(true)
    }
  })
})
