// Round 15 — group departures, tours, capacity.
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

// A query builder that records every call and resolves to no rows.
const calls: Array<[string, unknown[]]> = []
function builder(): unknown {
  const target = {
    then: (resolve: (v: unknown) => unknown) => resolve({ data: [], error: null }),
  }
  return new Proxy(target, {
    get(t, prop: string) {
      if (prop === 'then') return t.then
      return (...args: unknown[]) => {
        calls.push([prop, args])
        return builder()
      }
    },
  })
}

vi.mock('@supabase/supabase-js', () => ({ createClient: () => ({ from: (t: string) => { calls.push(['from', [t]]); return builder() } }) }))
vi.mock('@/lib/auth/current-org', () => ({
  getCurrentOrgId: async () => 'org-A',
  noOrgResponse: () => new Response(JSON.stringify({ success: false }), { status: 403 }),
}))
vi.mock('@/lib/org-identity', () => ({ orgIdentity: async () => ({ name: 'Nile <b>Journeys</b>' }) }))
vi.mock('@/lib/org-rate-currency', () => ({ getOrgRateCurrency: async () => 'JPY' }))
vi.mock('@/lib/pdf-fonts-server', () => ({ getJapaneseFontFace: async () => '' }))
vi.mock('@/lib/i18n/server-messages', () => ({
  getServerLocale: async () => 'en',
  lookupServerMessage: (_l: string, key: string, vars?: Record<string, string>) => {
    if (key.endsWith('generatedBy')) return `Generated by ${vars?.company}`
    if (key.endsWith('dayN')) return 'Day {n}'
    if (key.endsWith('perPersonHint')) return '{rate} pp × {pax}'
    return key.split('.').pop()
  },
}))

import { mergeCapacityEntry } from '@/lib/capacity-availability'
import { POST as exportTour } from '@/app/api/tours/export-pdf/route'
import { POST as checkDepartures } from '@/app/api/departures/check/route'

const src = (p: string) => readFileSync(join(process.cwd(), p), 'utf8')

beforeEach(() => {
  calls.length = 0
})

describe('departures/check reads only the session org', () => {
  it('ignores an org_id in the body', async () => {
    const res = await checkDepartures(new Request('http://x', {
      method: 'POST',
      body: JSON.stringify({ org_id: 'org-B', month: '2026-11' }),
    }) as never)
    expect(res.status).toBe(200)
    const orgFilters = calls.filter(([m, a]) => m === 'eq' && a[0] === 'org_id').map(([, a]) => a[1])
    expect(orgFilters).toEqual(['org-A'])
  })

  it('a month is searched from its first day, not the last day of the month before', async () => {
    await checkDepartures(new Request('http://x', {
      method: 'POST',
      body: JSON.stringify({ month: '2099-03' }),
    }) as never)
    const gte = calls.find(([m, a]) => m === 'gte' && a[0] === 'start_date')
    const lte = calls.find(([m, a]) => m === 'lte' && a[0] === 'start_date')
    expect(gte?.[1][1]).toBe('2099-03-01')
    expect(lte?.[1][1]).toBe('2099-03-31')
  })

  it('source: no body org_id, no UTC today', () => {
    const s = src('app/api/departures/check/route.ts')
    expect(s).not.toMatch(/const\s*\{[^}]*\borg_id\b[^}]*\}\s*=\s*body/)
    expect(s).toContain('getCurrentOrgId()')
    expect(s).toContain('businessToday()')
    expect(s).not.toContain("new Date().toISOString().split('T')[0]")
  })
})

describe('tour export prints money in the org currency and escapes the org name', () => {
  it('JPY totals have no decimals; the company name and day number are escaped', async () => {
    const res = await exportTour(new Request('http://x', {
      method: 'POST',
      body: JSON.stringify({
        tour: { tour_name: 'Nile', tour_code: 'N-1', days: [{ day_number: '<i>1</i>', city: 'Cairo' }] },
        pax: '<b>2</b>',
        is_euro_passport: false,
        pricing: { totals: { total_accommodation: 120000, grand_total: 345678 }, per_person: 172839 },
      }),
    }) as never)
    const html = await res.text()
    expect(html).toContain('¥345,678')
    expect(html).not.toContain('345678.00')
    expect(html).not.toContain('<b>Journeys</b>')
    expect(html).toContain('Nile &lt;b&gt;Journeys&lt;/b&gt;')
    expect(html).not.toContain('<i>1</i>')
    expect(html).not.toContain('<b>2</b>')
  })
})

describe('capacity saves keep what the request left out', () => {
  const stored = {
    status: 'busy', max_groups: 4, booked_groups: 4, booked_guides: 2, booked_vehicles: 3,
    internal_notes: 'Two coaches on hold', notes: 'Eid', reason: 'holiday', max_guides: 5, max_vehicles: 6,
  }

  it('a status-only edit keeps the booked counts and internal notes', () => {
    const row = mergeCapacityEntry({ status: 'limited' }, stored)
    expect(row.status).toBe('limited')
    expect(row.booked_groups).toBe(4)
    expect(row.booked_guides).toBe(2)
    expect(row.booked_vehicles).toBe(3)
    expect(row.internal_notes).toBe('Two coaches on hold')
    expect(row.max_guides).toBe(5)
  })

  it('a new day gets the defaults; given values (even blank ones) win', () => {
    expect(mergeCapacityEntry({}, null)).toMatchObject({ status: 'available', max_groups: 3, booked_groups: 0, internal_notes: null })
    expect(mergeCapacityEntry({ notes: '', booked_groups: 1 }, stored)).toMatchObject({ notes: '', booked_groups: 1 })
  })

  it('both save routes merge with the stored day', () => {
    for (const f of ['app/api/capacity/route.ts', 'app/api/capacity/[date]/route.ts']) {
      const s = src(f)
      expect(s).toContain('mergeCapacityEntry(')
      expect(s).not.toContain('booked_groups: entry.booked_groups ?? 0')
      expect(s).not.toContain('booked_groups: body.booked_groups ?? 0')
    }
  })

  it('the availability check counts default slots as slots left, and steps dates as strings', () => {
    const s = src('app/api/capacity/check/route.ts')
    expect(s).not.toContain('3 - group_size')
    expect(s).toContain('shiftDateISO(d, 1)')
  })
})

describe('departures', () => {
  it('end dates are calendar arithmetic, not a UTC parse with local setDate', () => {
    for (const f of ['app/api/departures/route.ts', 'app/api/departures/[id]/route.ts']) {
      const s = src(f)
      expect(s).toContain('shiftDateISO(')
      expect(s).not.toContain('endDateObj.setDate(')
    }
  })

  it('"upcoming" uses the caller\'s today, which the page sends', () => {
    expect(src('app/api/departures/route.ts')).toContain('todayFromRequest(request.url)')
    expect(src('app/api/departures/route.ts')).not.toContain("new Date().toISOString().split('T')[0]")
    expect(src('app/departures/page.tsx')).toContain('upcoming=true&today=${todayLocal()}')
  })

  it('a single departure reads booking columns that exist', () => {
    const s = src('app/api/departures/[id]/route.ts')
    expect(s).toContain('id, client_id, itinerary_id, client_name, pax, status, notes, created_at')
    expect(s).not.toContain('booking_name')
  })

  it('seats cannot be cut below the booked pax on the server', () => {
    const s = src('app/api/departures/[id]/route.ts')
    expect(s).toContain('if (bookedPax > maxPax)')
  })

  it('the active-bookings count before a delete is org-scoped', () => {
    const s = src('app/api/departures/[id]/route.ts')
    expect(s).toMatch(/\.eq\('departure_id', id\)\s*\n\s*\.eq\('org_id', org_id\)/)
  })

  it('a clone keeps its price currency', () => {
    const s = src('app/departures/page.tsx')
    expect(s).toContain("currency: departure.currency || 'EUR'")
    expect(s).toContain('Price per Person ({newDeparture.currency})')
  })
})

describe('tours', () => {
  it('the catalogue "starting from" tile converts from the rate currency, like the cards', () => {
    const s = src('app/tours/tours-browser-page.tsx')
    expect(s).not.toContain("as number)), 'EUR')")
  })

  it('the tour page defaults its travel date from the local today', () => {
    const s = src('app/tours/[code]/page.tsx')
    expect(s).toContain('shiftDateISO(todayLocalISO(), 14)')
  })
})
