import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { voucherMoney } from '@/lib/documents/plan-documents'
import { receiptNumberFor } from '@/lib/receipt-pdf-generator'
import { withCurrencyColumn } from '@/lib/finance-export'
import { roundToCurrency } from '@/lib/currency-totals'

const src = (p: string) => readFileSync(join(process.cwd(), p), 'utf8')

describe('voucherMoney', () => {
  it("states a supplier's own currency and cost while it agrees with the line's total", () => {
    const m = voucherMoney([
      { total_cost: 45000, supplier_currency: 'EGP', supplier_cost_original: 15000, exchange_rate_used: 3 },
      { total_cost: 3000, supplier_currency: 'egp', supplier_cost_original: 1000, exchange_rate_used: 3 },
    ], 'JPY')
    expect(m).toEqual({ currency: 'EGP', total: 16000, lineAmounts: [15000, 1000] })
  })
  it('never states a stale original: a line edited after it was priced uses its current total', () => {
    // Created at 2 rooms (EGP 15,000 = ¥45,000); edited to 3 rooms (¥67,500).
    const m = voucherMoney([{ total_cost: 67500, supplier_currency: 'EGP', supplier_cost_original: 15000, exchange_rate_used: 3 }], 'JPY')
    expect(m).toEqual({ currency: 'JPY', total: 67500, lineAmounts: [67500] })
  })
  it("stays in the trip's currency when the lines mix currencies, lack the original, or are already in it", () => {
    expect(voucherMoney([
      { total_cost: 100, supplier_currency: 'EGP', supplier_cost_original: 3000, exchange_rate_used: 1 / 30 },
      { total_cost: 50, supplier_currency: 'USD', supplier_cost_original: 55, exchange_rate_used: 50 / 55 },
    ], 'EUR')).toEqual({ currency: 'EUR', total: 150, lineAmounts: [100, 50] })
    expect(voucherMoney([{ total_cost: 80, supplier_currency: null, supplier_cost_original: null }], 'EUR').currency).toBe('EUR')
    // Same currency as the trip: total_cost, even if the stored original is stale.
    expect(voucherMoney([{ total_cost: 90, supplier_currency: 'EUR', supplier_cost_original: 60, exchange_rate_used: 1 }], 'EUR').total).toBe(90)
  })
})

describe('receipt numbers', () => {
  it('one rule everywhere: the transaction reference, else RCP- and the payment id', () => {
    expect(receiptNumberFor({ id: 'abcdef12-3456', transaction_reference: 'TX-9' })).toBe('TX-9')
    expect(receiptNumberFor({ id: 'abcdef12-3456', transaction_reference: null })).toBe('RCP-ABCDEF12')
    expect(src('app/invoices/[id]/page.tsx')).not.toContain('payments.indexOf(payment) + 1')
  })
})

describe('finance exports', () => {
  it('add a currency column when the rows have one', () => {
    const cols = [{ key: 'amount', label: 'Amount' }]
    expect(withCurrencyColumn([{ amount: 1, currency: 'JPY' }], cols).map(c => c.key)).toEqual(['amount', 'currency'])
    expect(withCurrencyColumn([{ amount: 1 }], cols)).toBe(cols)
    expect(withCurrencyColumn([{ amount: 1, currency: 'JPY' }], [...cols, { key: 'currency', label: 'Cur' }]).length).toBe(2)
  })
  it('print no platform brand', () => {
    expect(src('lib/finance-export.ts')).not.toContain("doc.text('AUTOURA'")
    expect(src('lib/finance-export.ts')).not.toContain('Generated by Autoura')
  })
})

describe('final invoice', () => {
  it('a stored trip cost reproduces the deposit where the rebuilt one cannot', () => {
    // 20% of ¥1,854,367 → ¥370,873. Rebuilt: 370,873 × 100 / 20 = ¥1,854,365.
    const deposit = roundToCurrency(1854367 * 0.2, 'JPY')
    expect(deposit).toBe(370873)
    expect((deposit * 100) / 20).toBe(1854365)
    expect(roundToCurrency(1854367 * 0.2, 'JPY')).toBe(deposit)
    expect(src('app/api/invoices/route.ts')).toContain("select('total_amount, currency, full_trip_cost')")
  })
})

describe('partner quote PDF terms', () => {
  const pdf = src('app/api/b2b/quotes/[id]/pdf/route.ts')
  it("states the organisation's own payment rule, not a fixed 30% / 14 days", () => {
    expect(pdf).toContain('paymentRuleFrom(orgRow')
    for (const fixed of ['labels.paymentDeposit}', 'labels.paymentBalance}', 'labels.cancelGenerous', 'labels.includesGuide', 'labels.includesWater']) {
      expect(pdf).not.toContain(fixed)
    }
  })
  it("uses the quote's language version, but not its placeholder title", () => {
    expect(pdf).toContain(".from('quote_versions')")
    expect(pdf).toContain('t.includes(String(quote.quote_number))')
    expect(pdf).toContain('labels.specialRequests')
  })
})

describe('client quote PDF terms', () => {
  it('prints no invented payment terms', () => {
    const gen = src('lib/pdf-generator.ts')
    expect(gen).not.toContain("'30% deposit required to confirm booking'")
    expect(gen).toContain('opts.paymentTerms')
  })
})

describe('quote convert', () => {
  it('never dates a trip today', () => {
    const route = src('app/api/b2b/quotes/[id]/convert/route.ts')
    expect(route).not.toContain('quote.travel_date ? new Date(quote.travel_date) : new Date()')
  })
})
