import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import { ScreenshotPlaceholder, Tip } from '../layout'

export default function NotificationsPage() {
  return (
    <div>
      {/* Breadcrumb */}
      <nav className="flex items-center gap-2 text-sm text-gray-500 mb-6">
        <Link href="/docs" className="hover:text-primary-600 transition-colors">Docs</Link>
        <ChevronRight className="w-4 h-4" />
        <span className="text-gray-900 font-medium">Notifications</span>
      </nav>

      <h1 className="text-3xl font-bold text-gray-900 mb-4">Notifications</h1>
      <p className="text-gray-600 mb-8">
        Notifications keep each team member informed about the work that needs their attention &mdash; from task assignments to incoming WhatsApp messages. They appear in a dedicated feed, can trigger an email, and link straight to the relevant record.
      </p>

      {/* Types */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Notification Types</h2>
        <p className="text-gray-600 mb-3">
          Notifications are color-coded and grouped by source:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          <li><strong>Tasks</strong> &mdash; Assigned, due soon, overdue, and completed</li>
          <li><strong>WhatsApp</strong> &mdash; Conversation assigned, new message, and mentions</li>
          <li><strong>Other events</strong> &mdash; Invoice paid, booking confirmed, and new client created</li>
        </ul>
        <ScreenshotPlaceholder caption="Notification feed with color-coded, icon-tagged items" />
      </section>

      {/* The feed */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">The Feed</h2>
        <p className="text-gray-600 mb-3">
          Each notification card shows an icon, title, type badge, message, and a relative timestamp (for example &ldquo;5 minutes ago&rdquo;). From a card you can:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          <li><strong>Open</strong> &mdash; Follow the link to the task or chat; WhatsApp items open the conversation</li>
          <li><strong>Mark Read</strong> &mdash; Clear a single notification</li>
          <li><strong>Delete</strong> &mdash; Remove it from the feed</li>
        </ul>
        <p className="text-gray-600 mt-3">
          Items that triggered an email show an <strong>email sent</strong> marker. Opening a notification&apos;s link marks it read automatically.
        </p>
      </section>

      {/* Stats & filters */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Stats &amp; Filtering</h2>
        <p className="text-gray-600 mb-3">
          Summary cards count total, unread, WhatsApp, and task notifications. Refine the feed with:
        </p>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          <li><strong>Search</strong> &mdash; By title or message text</li>
          <li><strong>All / Unread Only</strong> &mdash; Hide everything you&apos;ve already seen</li>
          <li><strong>Type</strong> &mdash; Filter to a specific WhatsApp or task event</li>
        </ul>
        <p className="text-gray-600 mt-3">
          When you have unread items, <strong>Mark All Read</strong> clears the whole feed in one click.
        </p>
      </section>

      {/* Where they come from */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Where Notifications Come From</h2>
        <p className="text-gray-600 mb-3">
          Notifications are generated by actions elsewhere in the app. For example, assigning a task creates a <strong>task_assigned</strong> notification for the new owner, optionally sending them an email as well.
        </p>
        <Tip>
          The feed loads the latest 100 notifications. Mark items read or delete them to keep it focused on what still needs action.
        </Tip>
      </section>

      {/* Navigation */}
      <div className="mt-12 pt-6 border-t border-gray-200 flex justify-between">
        <Link href="/docs" className="flex items-center gap-2 text-sm text-gray-600 hover:text-primary-600 transition-colors">
          <ChevronRight className="w-4 h-4 rotate-180" />
          All Docs
        </Link>
        <Link href="/docs/tasks" className="flex items-center gap-2 text-sm text-gray-600 hover:text-primary-600 transition-colors">
          Next: Tasks
          <ChevronRight className="w-4 h-4" />
        </Link>
      </div>
    </div>
  )
}
