// PDF Export API Endpoint
// Location: /app/api/tours/export-pdf/route.ts
//
// Returns an HTML document that the operator's browser can print. Not a
// puppeteer route — but JA characters still need the bundled font, since
// the deploy container's system fonts may not include CJK and the user
// may print from a kiosk/print server with the same gap. We embed
// NotoSansJP via @font-face for both EN and JA so the print result is
// self-contained.

import { NextRequest, NextResponse } from 'next/server'
import { getServerLocale, lookupServerMessage } from '@/lib/i18n/server-messages'
import { getJapaneseFontFace } from '@/lib/pdf-fonts-server'
import { getCurrentOrgId } from '@/lib/auth/current-org'
import { orgIdentity } from '@/lib/org-identity'
const supabaseAdmin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)
import { getOrgRateCurrency } from '@/lib/org-rate-currency'
import { formatMoney } from '@/lib/currency-totals'
import { createClient } from '@supabase/supabase-js'
import { escapeHtml } from '@/lib/html-escape'

/** Request-body text in the exported page: escaped, and blank for null. */
const esc = (v: unknown) => escapeHtml(v == null ? '' : String(v))

function contentDisposition(code: string): string {
  const ascii = code.replace(/[^\w.-]+/g, '_').slice(0, 80) || 'tour'
  return `attachment; filename="${ascii}.html"; filename*=UTF-8''${encodeURIComponent(code)}.html`
}

export async function POST(request: NextRequest) {
  try {
    // Rate amounts in text carry the org's rate-currency symbol, never a hard-coded euro.
    const orgId = await getCurrentOrgId()
    const rateCurrency = await getOrgRateCurrency(supabaseAdmin, orgId)
    const { tour, pax, is_euro_passport, pricing } = await request.json()

    const locale = await getServerLocale()
    const labelKeys = [
      'itinerary', 'tourCode', 'tourInformation', 'passengers', 'passportType',
      'passportEU', 'passportNonEU', 'tourSuffix', 'daysCities', 'dayN',
      'accommodation', 'lunch', 'dinner', 'guide', 'guideIncluded', 'notes',
      'pricingSummary', 'meals', 'guides', 'transportation', 'entrances',
      'total', 'perPersonHint', 'saveAsPdfHint', 'printButton', 'generatedBy',
    ]
    const labels: Record<string, string> = Object.fromEntries(
      labelKeys.map(k => [k, lookupServerMessage(locale, `pdf.tour.${k}`)])
    )
    // "Generated by …" names a company, so it comes from the organization and
    // not from the message catalogue, which used to hardcode the first
    // operator's name into both languages. With no name set the credit line
    // simply is not printed — the date below it still is.
    const identity = orgId ? await orgIdentity(orgId) : null
    labels.generatedBy = identity?.name
      ? lookupServerMessage(locale, 'pdf.tour.generatedBy', { company: identity.name })
      : ''
    const fontFace = await getJapaneseFontFace()

    const html = generateTourHTML(tour, pax, is_euro_passport, pricing, locale, labels, fontFace, rateCurrency)

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        // An ASCII-safe filename plus the UTF-8 one: a quote or a non-Latin-1
        // character in the tour code made the header invalid, and the export
        // failed with a 500.
        'Content-Disposition': contentDisposition(String(tour?.tour_code || 'tour'))
      }
    })

  } catch (error) {
    console.error('PDF export error:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to export PDF' },
      { status: 500 }
    )
  }
}

function generateTourHTML(
  tour: any,
  pax: number,
  isEuro: boolean,
  pricing: any,
  locale: 'en' | 'ja',
  labels: Record<string, string>,
  fontFace: string,
  rateCurrency: string,
) {
  // A missing total prints 0 rather than failing the whole export. In the
  // currency's own units: toFixed(2) printed ¥12,345 as "¥12345.00".
  const formatCurrency = (amount: number) => formatMoney(Number(amount) || 0, rateCurrency)
  const tag = locale === 'ja' ? 'ja-JP' : 'en-US'
  const generatedDate = new Date().toLocaleDateString(tag)

  return `
<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <title>${esc(tour.tour_name)} - ${labels.itinerary}</title>
  <style>
    ${fontFace}
    body {
      font-family: 'NotoSansJP', Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #1e40af;
      margin: 0;
    }
    .header p {
      color: #6b7280;
      margin: 5px 0;
    }
    .info-box {
      background: #eff6ff;
      border-left: 4px solid #2563eb;
      padding: 15px;
      margin: 20px 0;
    }
    .day-section {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
      page-break-inside: avoid;
    }
    .day-header {
      background: #2563eb;
      color: white;
      padding: 10px 15px;
      border-radius: 5px;
      margin: -20px -20px 15px -20px;
    }
    .service-item {
      margin: 10px 0;
      padding: 10px;
      background: #f9fafb;
      border-radius: 4px;
    }
    .service-item strong {
      color: #1f2937;
    }
    .pricing-summary {
      background: #f0fdf4;
      border: 2px solid #10b981;
      border-radius: 8px;
      padding: 20px;
      margin: 30px 0;
    }
    .pricing-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #d1fae5;
    }
    .pricing-total {
      font-size: 1.5em;
      font-weight: bold;
      color: #047857;
      margin-top: 15px;
      padding-top: 15px;
      border-top: 3px solid #10b981;
    }
    @media print {
      body { margin: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏛️ ${esc(tour.tour_name)}</h1>
    <p>${labels.tourCode}: ${esc(tour.tour_code)}</p>
    <p>${labels.daysCities.replace('{days}', esc(tour.duration_days ?? '')).replace('{cities}', esc((tour.cities || []).join(' → ')))}</p>
    <p style="text-transform: capitalize;">${esc(tour.tour_type)} ${labels.tourSuffix}</p>
  </div>

  <div class="info-box">
    <strong>📋 ${labels.tourInformation}</strong><br>
    👥 ${labels.passengers}: ${esc(pax)}<br>
    🛂 ${labels.passportType}: ${isEuro ? labels.passportEU : labels.passportNonEU}<br>
    ${tour.description ? `📝 ${esc(tour.description)}<br>` : ''}
  </div>

  ${(tour.days || []).map((day: any) => `
    <div class="day-section">
      <div class="day-header">
        <strong>${labels.dayN.replace('{n}', esc(day.day_number))}</strong> - ${esc(day.city)}
      </div>

      ${day.accommodation ? `
        <div class="service-item">
          <strong>🏨 ${labels.accommodation}:</strong> ${esc(day.accommodation.property_name)}<br>
          <small>${'⭐'.repeat(Math.max(0, Math.min(7, Number(day.accommodation.star_rating) || 0)))} ${esc(day.accommodation.tier)} • ${esc(day.accommodation.board_basis)} • ${esc(day.accommodation.room_type)}</small>
        </div>
      ` : ''}

      ${day.lunch_meal ? `
        <div class="service-item">
          <strong>🥗 ${labels.lunch}:</strong> ${esc(day.lunch_meal.restaurant_name)}<br>
          <small>${esc(day.lunch_meal.cuisine_type)} • ${esc(day.lunch_meal.restaurant_type)}</small>
        </div>
      ` : ''}

      ${day.dinner_meal ? `
        <div class="service-item">
          <strong>🍽️ ${labels.dinner}:</strong> ${esc(day.dinner_meal.restaurant_name)}<br>
          <small>${esc(day.dinner_meal.cuisine_type)} • ${esc(day.dinner_meal.restaurant_type)}</small>
        </div>
      ` : ''}

      ${day.guide_required ? `
        <div class="service-item">
          <strong>👨‍🏫 ${labels.guide}:</strong> ${labels.guideIncluded}
        </div>
      ` : ''}

      ${day.notes ? `
        <div class="service-item">
          <strong>📝 ${labels.notes}:</strong> ${esc(day.notes)}
        </div>
      ` : ''}
    </div>
  `).join('')}

  ${pricing ? `
    <div class="pricing-summary">
      <h2 style="margin-top: 0; color: #047857;">💰 ${labels.pricingSummary}</h2>

      <div class="pricing-row">
        <span>🏨 ${labels.accommodation}</span>
        <strong>${formatCurrency(pricing.totals.total_accommodation)}</strong>
      </div>
      <div class="pricing-row">
        <span>🍽️ ${labels.meals}</span>
        <strong>${formatCurrency(pricing.totals.total_meals)}</strong>
      </div>
      <div class="pricing-row">
        <span>👨‍🏫 ${labels.guides}</span>
        <strong>${formatCurrency(pricing.totals.total_guides)}</strong>
      </div>
      <div class="pricing-row">
        <span>🚗 ${labels.transportation}</span>
        <strong>${formatCurrency(pricing.totals.total_transportation)}</strong>
      </div>
      <div class="pricing-row">
        <span>🎫 ${labels.entrances}</span>
        <strong>${formatCurrency(pricing.totals.total_entrances)}</strong>
      </div>

      <div class="pricing-total">
        <div style="display: flex; justify-content: space-between;">
          <span>${labels.total}</span>
          <span>${formatCurrency(pricing.totals.grand_total)}</span>
        </div>
        <div style="font-size: 0.7em; font-weight: normal; margin-top: 5px;">
          ${labels.perPersonHint.replace('{rate}', formatCurrency(pricing.per_person)).replace('{pax}', esc(pax))}
        </div>
      </div>
    </div>
  ` : ''}

  <div class="no-print" style="text-align: center; margin: 30px 0; padding: 20px; background: #f3f4f6; border-radius: 8px;">
    <p><strong>${labels.saveAsPdfHint}</strong></p>
    <button onclick="window.print()" style="background: #2563eb; color: white; border: none; padding: 10px 30px; border-radius: 5px; cursor: pointer; font-size: 16px;">
      🖨️ ${labels.printButton}
    </button>
  </div>

  <div style="text-align: center; color: #9ca3af; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
    ${labels.generatedBy ? `${esc(labels.generatedBy)} • ` : ''}${generatedDate}
  </div>
</body>
</html>
  `
}
